import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/adapters.dart';
import 'package:path_provider/path_provider.dart';
import 'package:travel_app/features/data/models/trip_model.dart';
import 'package:travel_app/features/presentation/pages/main_screen.dart';

void main() async{
  WidgetsFlutterBinding.ensureInitialized();

await Hive.initFlutter((await getApplicationDocumentsDirectory()).path);
Hive.registerAdapter(TripModelAdapter()); // generated by hive generator file.g.dart
  await Hive.openBox<TripModel>('trips');

  runApp(ProviderScope(child: const MyApp()));
}

class MyApp extends StatelessWidget {
  
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Travel App',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.deepPurple),
        useMaterial3: true,
      ),
      debugShowCheckedModeBanner: false, // remove debug label
      home: MainScreen(),
    );
  }
}
